export const FETCH_ARTICLES_START = 'FETCH_ARTICLES_START';
export const FETCH_ARTICLES_DONE = 'FETCH_ARTICLES_DONE';
export const FETCH_ARTICLES_ERROR = 'FETCH_ARTICLES_ERROR';

export const FETCH_MY_ARTICLES_START = 'FETCH_MY_ARTICLES_START';
export const FETCH_MY_ARTICLES_DONE = 'FETCH_MY_ARTICLES_DONE';
export const FETCH_MY_ARTICLES_ERROR = 'FETCH_MY_ARTICLES_ERROR';

export const DELETE_ARTICLE_START = 'DELETE_ARTICLE_START';
export const DELETE_ARTICLE_DONE = 'DELETE_ARTICLE_DONE';
export const DELETE_ARTICLE_ERROR = 'DELETE_ARTICLE_ERROR';

