export const FETCH_ARTICLES_START = 'FETCH_ARTICLES_START';
export const FETCH_ARTICLES_DONE = 'FETCH_ARTICLES_DONE';
export const FETCH_ARTICLES_ERROR = 'FETCH_ARTICLES_ERROR';

export const FETCH_MY_ARTICLES_START = 'FETCH_MY_ARTICLES_START';
export const FETCH_MY_ARTICLES_DONE = 'FETCH_MY_ARTICLES_DONE';
export const FETCH_MY_ARTICLES_ERROR = 'FETCH_MY_ARTICLES_ERROR';

