export const POST_ARTICLE_START = 'POST_ARTICLE_START';
export const POST_ARTICLE_DONE = 'POST_ARTICLE_DONE';
export const POST_ARTICLE_ERROR = 'POST_ARTICLE_ERROR';
export const CHANGE_CONTENT = 'CHANGE_CONTENT';
export const CHANGE_TITLE = 'CHANGE_TITLE';
export const SET_TYPE = 'SET_TYPE'; // 设置文章类型 1. 富文本; 2. markdown

export const INIT_EDIT_ARTICLE_START = 'INIT_EDIT_ARTICLE_START';
export const INIT_EDIT_ARTICLE_SUCCESS = 'INIT_EDIT_ARTICLE_SUCCESS';
export const INIT_EDIT_ARTICLE_DONE = 'INIT_EDIT_ARTICLE_DONE';
