export const POST_ARTICLE_START = 'POST_ARTICLE_START';
export const POST_ARTICLE_DONE = 'POST_ARTICLE_DONE';
export const POST_ARTICLE_ERROR = 'POST_ARTICLE_ERROR';
export const CHANGE_CONTENT = 'CHANGE_CONTENT';
export const CHANGE_TITLE = 'CHANGE_TITLE';