import 'tinymce/plugins/code/plugin.js';
import 'tinymce/plugins/autoresize/plugin.js';
import 'tinymce/plugins/paste/plugin.js';
import 'tinymce/plugins/searchreplace/plugin.js';
import 'tinymce/plugins/link/plugin.js';
import 'tinymce/plugins/image/plugin.js';
import 'tinymce/plugins/table/plugin.js';
import './autofloat';
import './images';
